import Head from 'next/head'
import MainContent from '../files/components/MainContent'

export default function Home() {
  return (
    <>
      <Head>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Zachary Pagliaro</title>

      </Head>
      <div className="bg-body text-white font-poppins pb-12">
        <MainContent />
      </div>
    </>
  )
}

